services:

  wordpress:
    ports:
      - ${PORT_HOST_WORDPRESS}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: '1'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
    volumes:
      - ${WORDPRESS_DIR}:/var/www/html
    build:
      context: ./wordpress
      args:
        - WP_IMAGE_TAG=${WP_IMAGE_TAG}
        - XDEBUG=${XDEBUG}

  wordpress-cli:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ${WORDPRESS_DIR}:/var/www/html
    init: true
    command: [ "tail", "-f", "/dev/null" ]

  node:
    image: node
    volumes:
      - ${WORDPRESS_DIR}:/app
    init: true
    command: [ "tail", "-f", "/dev/null" ]
    working_dir: ${NODE_WORKING_DIR}

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_dockofony_wp:/var/lib/mysql

volumes:
  db_dockofony_wp:
